export const products = [
  {
    id: "1",
    name: "Tattoo-Inspired Coffee Mug",
    price: 15.99,
    description: "A ceramic coffee mug with a bold tattoo-inspired design.",
    categories: ["cups", "home", "tattoo accessories"],
    destacado: true,
    image: "https://source.unsplash.com/200x200/?coffee,mug",
  },
  {
    id: "2",
    name: "Tattoo-Themed T-Shirt",
    price: 25.00,
    description: "A comfortable T-shirt featuring a classic tattoo design.",
    categories: ["apparel", "T-shirts"],
    destacado: true,
    image: "https://source.unsplash.com/200x200/?tshirt,tattoo",
  },
  {
    id: "3",
    name: "Temporary Tattoo Kit",
    price: 12.99,
    description: "A kit with a variety of temporary tattoos to try at home.",
    categories: ["tattoo kits", "temporary tattoos"],
    destacado: false,
    image: "https://source.unsplash.com/200x200/?tattoo,kit",
  },
  {
    id: "4",
    name: "Tattoo Studio Poster",
    price: 10.99,
    description: "A high-quality poster featuring an intricate tattoo design.",
    categories: ["posters", "decor"],
    destacado: false,
    image: "https://source.unsplash.com/200x200/?poster,design",
  },
  {
    id: "5",
    name: "Tattoo-Inspired Tote Bag",
    price: 18.50,
    description: "A durable tote bag with a unique tattoo-themed print.",
    categories: ["bags", "tote bags"],
    destacado: true,
    image: "https://source.unsplash.com/200x200/?bag,tattoo",
  },
  {
    id: "6",
    name: "Tattoo-Style Water Bottle",
    price: 22.99,
    description: "A stainless steel water bottle featuring bold tattoo designs.",
    categories: ["bottles", "accessories"],
    destacado: false,
    image: "https://source.unsplash.com/200x200/?water,bottle,tattoo",
  },
  {
    id: "7",
    name: "Tattoo Flash Sticker Pack",
    price: 9.99,
    description: "A pack of high-quality stickers featuring classic tattoo designs.",
    categories: ["stickers", "tattoo art"],
    destacado: true,
    image: "https://source.unsplash.com/200x200/?sticker,tattoo",
  },
  {
    id: "8",
    name: "Tattoo-Inspired Hoodie",
    price: 40.00,
    description: "A warm hoodie with a vibrant tattoo design on the back.",
    categories: ["apparel", "hoodies"],
    destacado: false,
    image: "https://source.unsplash.com/200x200/?hoodie,tattoo",
  },
  {
    id: "9",
    name: "Tattoo Artist Sketchbook",
    price: 14.99,
    description: "A sketchbook designed for creating tattoo ideas and sketches.",
    categories: ["art supplies", "sketchbooks"],
    destacado: true,
    image: "https://source.unsplash.com/200x200/?sketchbook,tattoo",
  },
  {
    id: "10",
    name: "Tattoo-Inspired Phone Case",
    price: 19.99,
    description: "A protective phone case with a bold tattoo-themed design.",
    categories: ["accessories", "phone cases"],
    destacado: false,
    image: "https://source.unsplash.com/200x200/?phonecase,tattoo",
  },
];
